KERNEL_PATH := device/xiaomi/lavender-kernel

# Kernel
TARGET_FORCE_PREBUILT_KERNEL := true
#BOARD_PREBUILT_DTBOIMAGE := $(KERNEL_PATH)/dtbo.img
TARGET_PREBUILT_DTB := $(KERNEL_PATH)/sdm660-mtp-lavender.dtb
#BOARD_DTBOIMG_PARTITION_SIZE := 8388608
TARGET_PREBUILT_KERNEL := $(KERNEL_PATH)/Image.gz-dtb
#BOARD_MKBOOTIMG_ARGS += --dtb $(TARGET_PREBUILT_DTB)
